### ISSUE TITLE
A random one-line-art function. 

### ISSUE THREAD

**Issue by haraldfw** [tihlde/ircbot#18]
With the command >artme or something, the bot would print a random one-line "art"-piece in chat. Users might alsop be able to add art with the command >addart artpiecehere

**Comment by krissrex** [comment]
```
ヽ༼°ᴥ°༽ﾉ raise your doge ヽ༼°ᴥ°༽ﾉ

            wow

                           so donger
   ヽ༼°ᴥ°༽ﾉ
                                 wow
```


[ヽ༼ຈل͜ຈ༽ﾉ](https://www.reddit.com/r/raiseyourdongers)
